hardware_node:
  ros__parameters:
    wheel_cmd_topic: "/wheel_commands"
    wheel_ticks_topic: "/base/wheel_ticks4"
    ticks_frame_id: "base_link"

    # ---------------- Control ----------------
    # Control loop period (s)
    control_dt: 0.02

    # Encoder ticks per wheel revolution
    ticks_per_rev: 131000.0

    # ---------------- Speed estimation / filtering ----------------
    # speed_window_s is interpreted as a low-pass time constant tau (s)
    speed_window_s: 0.05

    # additional smoothing (0 = none, 1 = very strong)
    meas_alpha: 0.20

    # speeds below this are forced to zero (rad/s)
    meas_w_eps: 0.03

    # ---------------- Controller (P-TUNING) ----------------
    # Überschwingen → KP reduziert
    kp: 0.035
    ki: 0.0
    kd: 0.0

    output_limit: 1.0
    deadband: 0.10

    # moderate ramp, damit kein Setpoint-Schock
    setpoint_max_accel: 2.0

    # below this setpoint PID is reset and motor stopped
    stop_eps_radps: 0.10

    # ---------------- Actuator shaping (DISABLED for tuning) ----------------
    # slew rate limiting disabled
    u_slew_rate: 0.0

    # stiction compensation disabled
    u_min: 0.0
    u_min_apply_radps: 0.35

    # start kick disabled
    u_kick: 0.0
    kick_time_s: 0.0

    # ---------------- Hardware ----------------
    i2c_dev: "/dev/i2c-1"
    i2c_addr: 88

    wheel_channels: [2, 3, 0, 1]
    wheel_gains:    [1.0, 1.0, 1.0, 1.0]

    k_us_per_pct: 5.5
    neutral_us: 1480
    min_us: 900
    max_us: 2100
    pct_min: -100
    pct_max: 100

    phidget_serial: -1
    encoder_channels: [2, 3, 0, 1]

    invert_fl: true
    invert_fr: false
    invert_rl: true
    invert_rr: false

    publish_ticks_ms: 20
