hardware_node:
  ros__parameters:
    wheel_cmd_topic: "/wheel_commands"
    wheel_ticks_topic: "/base/wheel_ticks4"
    ticks_frame_id: "base_link"

    # Control loop period (s)
    control_dt: 0.02

    # Encoder ticks per wheel revolution
    ticks_per_rev: 131000.0

    # ---------------- Speed estimation / filtering ----------------
    # speed_window_s is interpreted as a *low-pass time constant* tau (s).
    # Smaller tau -> faster (less phase lag), more noise.
    # Larger tau -> smoother, more lag.
    speed_window_s: 0.05

    # Additional smoothing factor kept for backward compatibility.
    # 0.0 = no extra smoothing, 1.0 = very strong smoothing.
    meas_alpha: 0.20

    # Speeds below this are forced to 0 (rad/s) to suppress jitter.
    meas_w_eps: 0.03

    # ---------------- Controller (start values for tuning) ----------------
    # Start with PI disabled (ki=0) for the first tuning step.
    kp: 0.05
    ki: 0.00
    kd: 0.00

    output_limit: 1.0
    deadband: 0.10

    # Setpoint ramp limit (rad/s^2). Keep moderate during tuning.
    setpoint_max_accel: 2.0

    # If |setpoint| < stop_eps_radps -> motor command set to 0 and PID reset.
    stop_eps_radps: 0.10

    # ---------------- Actuator shaping / non-linearities ----------------
    # Slew limiting on u (1/s). 0 disables.
    # Disable during tuning to avoid extra lag.
    u_slew_rate: 0.0

    # Stiction compensation (minimum output when moving).
    # Disable during tuning (u_min=0), then re-enable if needed.
    u_min: 0.00
    # Apply u_min only if |setpoint| >= this threshold (rad/s)
    u_min_apply_radps: 0.35

    # Optional start kick (additive), keep OFF during tuning.
    u_kick: 0.00
    kick_time_s: 0.00

    # ---------------- Hardware ----------------
    i2c_dev: "/dev/i2c-1"
    i2c_addr: 88

    wheel_channels: [2, 3, 0, 1]
    wheel_gains:    [1.0, 1.0, 1.0, 1.0]

    k_us_per_pct: 5.5
    neutral_us: 1480
    min_us: 900
    max_us: 2100
    pct_min: -100
    pct_max: 100

    phidget_serial: -1
    encoder_channels: [2, 3, 0, 1]

    invert_fl: true
    invert_fr: false
    invert_rl: true
    invert_rr: false

    publish_ticks_ms: 20
