hardware_node:
  ros__parameters:
    i2c_dev: /dev/i2c-1
    i2c_addr: 0x58

    left_channels: [0, 2]
    right_channels: [1, 3]

    k_us_per_pct: 5.5
    neutral_us: 1480
    pct_min: -100
    pct_max: 100

    acceleration: 30
    watchdog_timeout_ms: 300
