hardware_node:
  ros__parameters:
    wheel_cmd_topic: "/wheel_commands"
    wheel_ticks_topic: "/base/wheel_ticks4"
    ticks_frame_id: "base_link"

    # ================= Control =================
    control_dt: 0.02        # 50 Hz Regelung
    ticks_per_rev: 131000.0

    # ================= Speed estimation =================
    # Low-pass time constant (kleiner = weniger Verzögerung)
    speed_window_s: 0.03

    # Zusatzglättung (klein halten, sonst Phasenverlust)
    meas_alpha: 0.10

    # Nullschwelle für Geschwindigkeit
    meas_w_eps: 0.01

    # ================= Controller (P-TUNING, stabil) =================
    kp: 0.040
    ki: 0.0
    kd: 0.0

    output_limit: 1.0

    # Totband klein, sonst Takten
    deadband: 0.02

    # Sollwert-Rampe (unproblematisch für drive_straight)
    setpoint_max_accel: 2.0

    # Unterhalb davon wird gestoppt + Regler zurückgesetzt
    stop_eps_radps: 0.05

    # ================= Actuator shaping =================
    # Slew-Rate aus, um keine Zusatzdynamik reinzubringen
    u_slew_rate: 0.0

    # Stiction-Kompensation aktiv gegen Ruckeln
    u_min: 0.12
    u_min_apply_radps: 0.25

    # Kick deaktiviert
    u_kick: 0.0
    kick_time_s: 0.0

    # ================= Hardware =================
    i2c_dev: "/dev/i2c-1"
    i2c_addr: 88

    wheel_channels: [2, 3, 0, 1]
    wheel_gains:    [1.0, 1.0, 1.0, 1.0]

    k_us_per_pct: 5.5
    neutral_us: 1480
    min_us: 900
    max_us: 2100
    pct_min: -100
    pct_max: 100

    phidget_serial: -1
    encoder_channels: [2, 3, 0, 1]

    invert_fl: true
    invert_fr: false
    invert_rl: true
    invert_rr: false

    publish_ticks_ms: 20
