hardware_node:
  ros__parameters:
    wheel_cmd_topic: "/wheel_commands"
    wheel_ticks_topic: "/base/wheel_ticks4"
    ticks_frame_id: "base_link"

    control_dt: 0.02

    # Phidget: 500 CPR * 4 * 65.5 = 131000 ticks / wheel rev
    ticks_per_rev: 131000.0

    # PID (Startwerte "anti-ruckeln" für low-speed)
    kp: 0.08
    ki: 0.35
    kd: 0.0

    output_limit: 1.0

    # etwas größer, um PWM/Mechanik-Totzone nicht ständig zu "flippen"
    deadband: 0.12

    # limit setpoint ramp (rad/s^2): zu hoch => ruckeln beim Anfahren
    setpoint_max_accel: 2.0

    # stop threshold (rad/s)
    stop_eps_radps: 0.05

    # Messwertfilter (0..1): kleiner => stärker glätten
    meas_alpha: 0.25
    meas_w_eps: 0.05

    # Ausgangsänderung begrenzen (0 disables). kleiner => weicheres Anfahren
    u_slew_rate: 1.5

    # I2C
    i2c_dev: "/dev/i2c-1"
    i2c_addr: 88

    # [FL, FR, RL, RR] servo channels
    wheel_channels: [2, 3, 0, 1]
    wheel_gains:    [1.0, 1.0, 1.0, 1.0]

    k_us_per_pct: 5.5
    neutral_us: 1480
    min_us: 900
    max_us: 2100
    pct_min: -100
    pct_max: 100

    # Phidget HighSpeed Encoder 1047
    phidget_serial: -1
    encoder_channels: [2, 3, 0, 1]

    # FL + RL invertiert
    invert_fl: true
    invert_fr: false
    invert_rl: true
    invert_rr: false

    publish_ticks_ms: 20
