hardware_node:
  ros__parameters:
    wheel_cmd_topic: "/wheel_commands"
    wheel_ticks_topic: "/base/wheel_ticks4"
    ticks_frame_id: "base_link"

    control_dt: 0.02
    ticks_per_rev: 131000.0

    # PID: ruhiger, mehr I gegen Reibung
    kp: 0.05
    ki: 0.40
    kd: 0.0
    output_limit: 1.0
    deadband: 0.10
    setpoint_max_accel: 1.2
    stop_eps_radps: 0.05

    # measurement smoothing
    meas_alpha: 0.20
    meas_w_eps: 0.03

    # KEY: noch längeres Fenster -> weniger low-speed "0/1 tick" Sägen
    speed_window_s: 0.15

    # output smoothing
    u_slew_rate: 0.8

    # stiction compensation
    u_min: 0.22
    u_kick: 0.00
    kick_time_s: 0.00

    i2c_dev: "/dev/i2c-1"
    i2c_addr: 88

    wheel_channels: [2, 3, 0, 1]
    wheel_gains:    [1.0, 1.0, 1.0, 1.0]

    k_us_per_pct: 5.5
    neutral_us: 1480
    min_us: 900
    max_us: 2100
    pct_min: -100
    pct_max: 100

    phidget_serial: -1
    encoder_channels: [2, 3, 0, 1]

    invert_fl: true
    invert_fr: false
    invert_rl: true
    invert_rr: false

    publish_ticks_ms: 20
