hardware_node:
  ros__parameters:
    i2c_dev: "/dev/i2c-1"
    i2c_addr: 0x58

    left_channels:  [2, 0]
    right_channels: [3, 1]
    wheel_channels: [2, 3, 0, 1]

    wheel_gains: [0.94, 1.10, 1.08, 0.91]
    ignore_wheel_gains: true   # NEU: Gains im Regelbetrieb deaktivieren

    k_us_per_pct: 5.5
    neutral_us: 1480
    min_us: 900
    max_us: 2100

    pct_min: -100
    pct_max: 100

    acceleration: 0            # für erste Regeltests empfohlen

    watchdog_timeout_ms: 300
    test_mode: false

    phidget_serial: -1
    encoder_channels: [2, 3, 0, 1]

    invert_fl: true
    invert_fr: false
    invert_rl: true
    invert_rr: false

    publish_ticks_ms: 20
