hardware_node:
  ros__parameters:
    wheel_cmd_topic: "/wheel_commands"
    wheel_ticks_topic: "/base/wheel_ticks4"
    ticks_frame_id: "base_link"

    # ================= Control =================
    control_dt: 0.02
    ticks_per_rev: 131000.0

    # ================= Speed estimation =================
    speed_window_s: 0.02
    meas_alpha: 0.10
    meas_w_eps: 0.005

    # ================= Controller (PI, sehr weich) =================
    kp: 0.045
    ki: 0.015
    kd: 0.0

    output_limit: 1.0
    deadband: 0.005

    setpoint_max_accel: 2.0
    stop_eps_radps: 0.02

    # ================= Actuator shaping =================
    u_slew_rate: 0.0

    # --- Stiction-Kompensation AUS (nur Diagnose gegen 2 Hz Limit-Cycle) ---
    u_min: 0.0
    u_min_apply_radps: 0.25

    u_kick: 0.0
    kick_time_s: 0.0

    # ================= Hardware =================
    i2c_dev: "/dev/i2c-1"
    i2c_addr: 88

    wheel_channels: [2, 3, 0, 1]
    wheel_gains:    [1.0, 1.0, 1.0, 1.0]

    k_us_per_pct: 5.5
    neutral_us: 1480
    min_us: 900
    max_us: 2100
    pct_min: -100
    pct_max: 100

    phidget_serial: -1
    encoder_channels: [2, 3, 0, 1]

    invert_fl: true
    invert_fr: false
    invert_rl: true
    invert_rr: false

    publish_ticks_ms: 20
