hardware_node:
  ros__parameters:
    wheel_cmd_topic: "/wheel_commands"
    wheel_ticks_topic: "/base/wheel_ticks4"
    ticks_frame_id: "base_link"

    control_dt: 0.02
    ticks_per_rev: 131000.0

    # PID (ruhig bei low speed)
    kp: 0.06
    ki: 0.30
    kd: 0.0
    output_limit: 1.0
    deadband: 0.10
    setpoint_max_accel: 1.5
    stop_eps_radps: 0.05

    # measurement smoothing
    meas_alpha: 0.25
    meas_w_eps: 0.03

    # KEY: speed estimate over longer window
    speed_window_s: 0.10

    # output smoothing
    u_slew_rate: 1.0

    # stiction compensation
    u_min: 0.18
    u_kick: 0.00
    kick_time_s: 0.00

    # I2C
    i2c_dev: "/dev/i2c-1"
    i2c_addr: 88

    # [FL, FR, RL, RR]
    wheel_channels: [2, 3, 0, 1]
    wheel_gains:    [1.0, 1.0, 1.0, 1.0]

    k_us_per_pct: 5.5
    neutral_us: 1480
    min_us: 900
    max_us: 2100
    pct_min: -100
    pct_max: 100

    # Phidget 1047
    phidget_serial: -1
    encoder_channels: [2, 3, 0, 1]

    # FL + RL invertiert
    invert_fl: true
    invert_fr: false
    invert_rl: true
    invert_rr: false

    publish_ticks_ms: 20
