hardware_node:
  ros__parameters:
    # topics
    wheel_cmd_topic: /wheel_commands
    wheel_ticks_topic: /base/wheel_ticks4
    ticks_frame_id: base_link

    # encoders (Phidget)
    phidget_serial: -1
    encoder_channels: [2, 3, 0, 1]   # [fl, fr, rl, rr]
    invert_fl: true
    invert_fr: false
    invert_rl: true
    invert_rr: false
    ticks_per_rev: 131000

    # motor controller (NXT Servo over I2C)
    i2c_dev: "/dev/i2c-1"
    i2c_addr: 0x58
    servo_channels: [0, 1, 2, 3]     # [fl, fr, rl, rr]

    # per-wheel PWM calibration
    k_us_per_pct_4: [5.5, 5.5, 5.5, 5.5]
    neutral_us_4:   [1480, 1480, 1480, 1480]
    min_us_4:       [900, 900, 900, 900]
    max_us_4:       [2100, 2100, 2100, 2100]
    pct_min: -100
    pct_max: 100
    accel: 100

    # control
    max_wheel_radps: 20.0
    watchdog_timeout_s: 0.3
    control_period_ms: 10
    publish_ticks_ms: 20

    # PID (Floribot1.0 style) - applied per wheel
    kp: 2.0
    ki: 0.5
    kd: 0.0
    output_limit: 1.0
    deadband: 0.05
    setpoint_max_accel: 2.0
