hardware_node:
  ros__parameters:
    wheel_cmd_topic: "/wheel_commands"
    wheel_ticks_topic: "/base/wheel_ticks4"
    ticks_frame_id: "base_link"

    control_dt: 0.02
    ticks_per_rev: 2048.0

    kp: 0.6
    ki: 0.0
    kd: 0.0
    output_limit: 1.0
    deadband: 0.0
    setpoint_max_accel: 1000000000.0

    # Encoder source: phidgets_high_speed_encoder publishes joint0..joint3 by default
    joint_states_topic: "/joint_states"
    fl_joint: "joint2"
    fr_joint: "joint3"
    rl_joint: "joint0"
    rr_joint: "joint1"

    invert_fl: false
    invert_fr: false
    invert_rl: false
    invert_rr: false

    # NXT Servo Controller (Pi mapping)
    i2c_dev: "/dev/i2c-1"
    i2c_addr: 88   # 0x58

    # Order: [FL, FR, RL, RR]
    wheel_channels: [2, 3, 0, 1]
    wheel_gains:    [1.0, 1.0, 1.0, 1.0]

    k_us_per_pct: 5.5
    neutral_us: 1480
    min_us: 900
    max_us: 2100
    pct_min: -100
    pct_max: 100
