kinematics_node:
  ros__parameters:
    cmd_vel_topic: /cmd_vel
    wheel_cmd_topic: /base/wheel_cmd
    wheel_ticks_topic: /base/wheel_ticks4
    odom_topic: /odom

    odom_frame: odom
    base_frame: base_link
    publish_tf: true

    wheel_base_m: 0.50
    wheel_radius_m: 0.10
    ticks_per_rev: 131000

    control_period_ms: 20
    cmd_timeout_ms: 300

    # NEU in der überarbeiteten Version:
    ticks_timeout_ms: 120
    min_ticks_dt_s: 0.005

    v_max_mps: 0.8
    use_feedforward: false   # für ersten Test empfohlen

    v_deadband_mps: 0.02
    pid_deadband_mps: 0.01

    kp: 18.0
    ki: 0.0
    kd: 0.0
    i_min: -50.0
    i_max: 50.0

    meas_lpf_alpha: 0.15
    min_pwm_pct: 8

    debug: true
