kinematics_node:
  ros__parameters:
    # Spurweite (wird als Nächstes über Rotation kalibriert)
    wheel_separation: 0.385

    # FINAL kalibrierter Radradius
    # odom: 2.0204 m
    # real: 2.115 m
    # Faktor: 1.04678
    wheel_radius: 0.09735

    ticks_per_rev: 131000.0
    unwrap_modulo: false
    modulo_ticks: 131000

    cmd_vel_topic: "/cmd_vel"
    wheel_cmd_topic: "/wheel_commands"
    wheel_ticks_topic: "/base/wheel_ticks4"
    odom_topic: "/odom"

    odom_frame_id: "odom"
    base_frame_id: "base_link"
    publish_tf: true
