kinematics_node:
  ros__parameters:
    # Rotation Korrektur:
    # odom: 6.284217 rad
    # real: 362° = 6.317718 rad
    # Faktor = odom/real = 0.99470
    # 0.8084 -> 0.8041
    wheel_separation: 0.8041

    wheel_radius: 0.09688

    ticks_per_rev: 131000.0
    unwrap_modulo: false
    modulo_ticks: 131000

    cmd_vel_topic: "/cmd_vel"
    wheel_cmd_topic: "/wheel_commands"
    wheel_ticks_topic: "/base/wheel_ticks4"
    odom_topic: "/odom"

    odom_frame_id: "odom"
    base_frame_id: "base_link"
    publish_tf: true
