kinematics_node:
  ros__parameters:
    wheel_separation: 0.385
    wheel_radius: 0.100

    ticks_per_rev: 2048.0
    unwrap_modulo: true
    modulo_ticks: 2048

    cmd_vel_topic: "/cmd_vel"
    wheel_cmd_topic: "/wheel_commands"
    wheel_ticks_topic: "/base/wheel_ticks4"
    odom_topic: "/odom"

    odom_frame_id: "odom"
    base_frame_id: "base_link"
    publish_tf: true
