kinematics_node:
  ros__parameters:
    # =========================
    # Topics
    # =========================
    cmd_vel_topic: /cmd_vel
    wheel_cmd4_topic: /base/wheel_cmd4
    wheel_cmd_topic: /base/wheel_cmd
    wheel_ticks_topic: /base/wheel_ticks4
    odom_topic: /odom

    # =========================
    # Frames
    # =========================
    odom_frame: odom
    base_frame: base_link
    publish_tf: true

    # =========================
    # Geometry / scaling
    # Spurbreite links–rechts (track width)
    # =========================
    track_width_m: 0.385
    # optional (deprecated override im Code vorhanden):
    wheel_base_m: 0.385

    wheel_radius_m: 0.10
    ticks_per_rev: 131000

    # =========================
    # Control loop & safety
    # =========================
    control_period_ms: 20
    cmd_timeout_ms: 300

    # =========================
    # Closed-loop control
    # =========================
    use_closed_loop: true
    use_feedforward: true

    # Aggressiveres Feedforward (mehr PWM bei gleichem Soll)
    v_max_mps: 0.4

    # =========================
    # Deadbands / friction
    # =========================
    v_deadband_mps: 0.03
    pid_deadband_mps: 0.02

    # Mindest-PWM gegen Haftreibung (wichtig für Drehung auf der Stelle)
    min_pwm_pct: 12

    # =========================
    # SIDE velocity controller gains (Skid-Steer)
    # =========================
    vel_kp: 35.0
    vel_ki: 10.0
    i_min: -40.0
    i_max: 40.0

    # =========================
    # Measurement filtering
    # =========================
    meas_lpf_alpha: 0.10

    # =========================
    # Optional: innerhalb einer Seite angleichen (nur wenn aktiviert)
    # =========================
    use_within_side_sync: true
    sync_k: 30.0

    # =========================
    # Debug
    # =========================
    debug: true
