kinematics_node:
  ros__parameters:
    # Rotation kalibriert:
    # odom stoppt bei 360°, real 171°
    # => b_new = b_old * 360/171
    # bei b_old=0.385 -> b_new=0.8105
    wheel_separation: 0.8105

    # FINAL kalibrierter Radradius
    wheel_radius: 0.09735

    ticks_per_rev: 131000.0
    unwrap_modulo: false
    modulo_ticks: 131000

    cmd_vel_topic: "/cmd_vel"
    wheel_cmd_topic: "/wheel_commands"
    wheel_ticks_topic: "/base/wheel_ticks4"
    odom_topic: "/odom"

    odom_frame_id: "odom"
    base_frame_id: "base_link"
    publish_tf: true
