kinematics_node:
  ros__parameters:
    wheel_separation: 0.385

    # Iteration:
    # Ziel: odom=2.00 m, real=1.865 m  -> Faktor = 1.865/2.00 = 0.9325
    # vorher: wheel_radius=0.1051 -> neu: 0.1051*0.9325 = 0.0980 m
    wheel_radius: 0.0980

    ticks_per_rev: 131000.0
    unwrap_modulo: false
    modulo_ticks: 131000

    cmd_vel_topic: "/cmd_vel"
    wheel_cmd_topic: "/wheel_commands"
    wheel_ticks_topic: "/base/wheel_ticks4"
    odom_topic: "/odom"

    odom_frame_id: "odom"
    base_frame_id: "base_link"
    publish_tf: true
