kinematics_node:
  ros__parameters:
    wheel_separation: 0.8105

    # Fein-Kalibrierung (Laser):
    # real 2.034 m, odom 2.043854715736173 m
    # Faktor = real/odom = 0.995178 -> Radius minimal kleiner
    wheel_radius: 0.09688

    ticks_per_rev: 131000.0
    unwrap_modulo: false
    modulo_ticks: 131000

    cmd_vel_topic: "/cmd_vel"
    wheel_cmd_topic: "/wheel_commands"
    wheel_ticks_topic: "/base/wheel_ticks4"
    odom_topic: "/odom"

    odom_frame_id: "odom"
    base_frame_id: "base_link"
    publish_tf: true
