kinematics_node:
  ros__parameters:
    wheel_separation: 0.385

    # Geometrisch: D=0.186 m -> r=0.093 m
    # Kalibriert: 2.00m Soll -> 2.15m Ist => r_new = 0.093 * 2.00/2.15 = 0.0865 m
    wheel_radius: 0.0865

    ticks_per_rev: 131000.0

    unwrap_modulo: false
    modulo_ticks: 131000

    cmd_vel_topic: "/cmd_vel"
    wheel_cmd_topic: "/wheel_commands"
    wheel_ticks_topic: "/base/wheel_ticks4"
    odom_topic: "/odom"

    odom_frame_id: "odom"
    base_frame_id: "base_link"
    publish_tf: true
