kinematics_node:
  ros__parameters:
    wheel_separation: 0.385

    # Kalibrierung:
    # Odom stoppt bei 2.00 m, real gemessen 2.26 m
    # => r_new = r_old * 2.26/2.00 = 0.093 * 1.13 = 0.1051 m
    wheel_radius: 0.1051

    ticks_per_rev: 131000.0

    unwrap_modulo: false
    modulo_ticks: 131000

    cmd_vel_topic: "/cmd_vel"
    wheel_cmd_topic: "/wheel_commands"
    wheel_ticks_topic: "/base/wheel_ticks4"
    odom_topic: "/odom"

    odom_frame_id: "odom"
    base_frame_id: "base_link"
    publish_tf: true
