kinematics_node:
  ros__parameters:
    wheel_separation: 0.385

    # Raddurchmesser 18.6 cm => Radius 0.093 m
    wheel_radius: 0.093

    # Phidget: 500 CPR * 4 * 65.5 = 131000 ticks / wheel revolution
    ticks_per_rev: 131000.0

    # continuous ticks (callback accumulated) -> no wrap
    unwrap_modulo: false
    modulo_ticks: 131000

    cmd_vel_topic: "/cmd_vel"
    wheel_cmd_topic: "/wheel_commands"
    wheel_ticks_topic: "/base/wheel_ticks4"
    odom_topic: "/odom"

    odom_frame_id: "odom"
    base_frame_id: "base_link"
    publish_tf: true
