kinematics_node:
  ros__parameters:
    # Translation neu kalibriert:
    # real: 2.279 m
    # odom: 2.099990087 m
    # Faktor = 1.08527
    # 0.09688 -> 0.10514
    wheel_radius: 0.1051

    # Rotation separat kalibrieren!
    wheel_separation: 0.8041

    ticks_per_rev: 131000.0
    unwrap_modulo: false
    modulo_ticks: 131000

    cmd_vel_topic: "/cmd_vel"
    wheel_cmd_topic: "/wheel_commands"
    wheel_ticks_topic: "/base/wheel_ticks4"
    odom_topic: "/odom"

    odom_frame_id: "odom"
    base_frame_id: "base_link"
    publish_tf: true
