kinematics_node:
  ros__parameters:
    # zurück auf plausible Spurweite (sonst wird bei kleinen Radien ein Rad rückwärts -> Pivot)
    wheel_separation: 0.385

    # so lassen, wenn geradeaus stimmt
    wheel_radius: 0.093

    ticks_per_rev: 131000.0
    unwrap_modulo: false
    modulo_ticks: 131000

    cmd_vel_topic: "/cmd_vel"
    wheel_cmd_topic: "/wheel_commands"
    wheel_ticks_topic: "/base/wheel_ticks4"
    odom_topic: "/odom"

    odom_frame_id: "odom"
    base_frame_id: "base_link"
    publish_tf: true
