kinematics_node:
  ros__parameters:
    # Translation-Korrektur:
    # real: 1.90 m
    # odom: 2.0269994787835475 m
    # Faktor = 0.937346
    # 0.1051 -> 0.09852
    wheel_radius: 0.09852

    # Rotation separat kalibriert lassen (unverändert)
    wheel_separation: 0.8041

    ticks_per_rev: 131000.0
    unwrap_modulo: false
    modulo_ticks: 131000

    cmd_vel_topic: "/cmd_vel"
    wheel_cmd_topic: "/wheel_commands"
    wheel_ticks_topic: "/base/wheel_ticks4"
    odom_topic: "/odom"

    odom_frame_id: "odom"
    base_frame_id: "base_link"
    publish_tf: true
