kinematics_node:
  ros__parameters:
    # =========================
    # Topics
    # =========================
    cmd_vel_topic: /cmd_vel
    wheel_cmd_topic: /base/wheel_cmd
    wheel_ticks_topic: /base/wheel_ticks4
    odom_topic: /odom

    # =========================
    # Frames
    # =========================
    odom_frame: odom
    base_frame: base_link
    publish_tf: true

    # =========================
    # Geometry / scaling
    # =========================
    wheel_base_m: 0.50
    wheel_radius_m: 0.10
    ticks_per_rev: 131000

    # =========================
    # Control loop & safety
    # =========================
    control_period_ms: 20
    cmd_timeout_ms: 300

    # =========================
    # Closed-loop control
    # =========================
    use_closed_loop: true
    use_feedforward: true
    v_max_mps: 0.8

    # =========================
    # Deadbands / friction
    # (bewusst größer für ruhigen Lauf)
    # =========================
    v_deadband_mps: 0.03
    pid_deadband_mps: 0.02
    min_pwm_pct: 0

    # =========================
    # Velocity controller gains
    # (nur P-Regler, bewusst weich)
    # =========================
    vel_kp: 25.0
    vel_ki: 0.0
    i_min: -20.0
    i_max: 20.0

    # =========================
    # Measurement filtering
    # =========================
    meas_lpf_alpha: 0.10

    # =========================
    # Debug
    # =========================
    debug: true
