kinematics_node:
  ros__parameters:
    # =========================
    # Topics
    # =========================
    cmd_vel_topic: /cmd_vel
    wheel_cmd4_topic: /base/wheel_cmd4
    wheel_cmd_topic: /base/wheel_cmd
    wheel_ticks_topic: /base/wheel_ticks4
    odom_topic: /odom

    # =========================
    # Frames
    # =========================
    odom_frame: odom
    base_frame: base_link
    publish_tf: true

    # =========================
    # Geometry / scaling
    #
    # Mit dem überarbeiteten Code wird primär "track_width_m" erwartet.
    # (wheel_base_m bleibt als Deprecated-Override erhalten.)
    # Spurbreite links–rechts (Abstand der Seiten) = 0.385 m
    # =========================
    track_width_m: 0.385
    # optional für alte Konfigurationen/Kompatibilität:
    wheel_base_m: 0.385

    wheel_radius_m: 0.10
    ticks_per_rev: 131000

    # =========================
    # Control loop & safety
    # =========================
    control_period_ms: 20
    cmd_timeout_ms: 300

    # =========================
    # Closed-loop control
    # =========================
    use_closed_loop: true
    use_feedforward: true
    v_max_mps: 0.8

    # =========================
    # Deadbands / friction
    # =========================
    v_deadband_mps: 0.03
    pid_deadband_mps: 0.02
    # Für Skid-Steer i.d.R. besser >0, damit Totzone/Haftreibung überwunden wird.
    # Startwert konservativ:
    min_pwm_pct: 8

    # =========================
    # SIDE velocity controller gains (Skid-Steer)
    # vel_kp, vel_ki gelten nun pro Seite (vL/vR), nicht pro Rad.
    # =========================
    vel_kp: 25.0
    # Für stationäre Genauigkeit bei unterschiedlichen Sabertooth-Kanälen sinnvoll aktivieren:
    vel_ki: 10.0
    i_min: -40.0
    i_max: 40.0

    # =========================
    # Measurement filtering
    # =========================
    meas_lpf_alpha: 0.10

    # =========================
    # Optional: innerhalb einer Seite angleichen (FL↔RL und FR↔RR)
    # =========================
    use_within_side_sync: false
    sync_k: 15.0

    # =========================
    # Debug
    # =========================
    debug: true
