kinematics_node:
  ros__parameters:
    # Rotation: 360° soll, 180° ist  => wheel_separation halbieren
    wheel_separation: 0.1925

    # so lassen, wenn geradeaus jetzt passt
    wheel_radius: 0.093

    ticks_per_rev: 131000.0
    unwrap_modulo: false
    modulo_ticks: 131000

    cmd_vel_topic: "/cmd_vel"
    wheel_cmd_topic: "/wheel_commands"
    wheel_ticks_topic: "/base/wheel_ticks4"
    odom_topic: "/odom"

    odom_frame_id: "odom"
    base_frame_id: "base_link"
    publish_tf: true
