kinematics_node:
  ros__parameters:
    wheel_separation: 0.385

    # korrigiert wegen +10% Wegfehler (2.0m Soll -> 2.2m Ist):
    # r_new = r_old * 2.0/2.2 = 0.100 * 0.90909 = 0.0909 m
    wheel_radius: 0.0909

    ticks_per_rev: 131000.0
    unwrap_modulo: false
    modulo_ticks: 131000

    cmd_vel_topic: "/cmd_vel"
    wheel_cmd_topic: "/wheel_commands"
    wheel_ticks_topic: "/base/wheel_ticks4"
    odom_topic: "/odom"

    odom_frame_id: "odom"
    base_frame_id: "base_link"
    publish_tf: true
