kinematics_node:
  ros__parameters:
    cmd_vel_topic: /cmd_vel
    wheel_cmd_topic: /wheel_commands

    # 4-wheel diff-drive geometry (same equations as 2-wheel diff-drive)
    track_width_m: 0.385
    wheel_radius_m: 0.10

    # safety limits applied to /cmd_vel
    v_max_mps: 0.4
    w_max_rps: 2.0
